/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export interface ResolverInternal {
  
}
export function create(options: string): ExternalObject<ResolverInternal>
export interface ResolveResult {
  status: boolean
  path?: string
}
export function resolve(resolver: ExternalObject<Resolver>, baseDir: string, id: string): ResolveResult
